# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            The Magyartanul√°s Repository
tagline:          'Free resource for learning hungarian'
description:      'Your Number #1 Repository for Hungarian Grammar!'
url:              magyartanulas.github.io
baseurl:          https://magyartanulas.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Magyartanulas/magyartanulas.github.io
